name: Mise à jour Ubuntu

on:
  push:
    branches: [ main, dev ]

jobs:
  update-system:
    runs-on: ubuntu-latest

    steps:
      - name: Mettre à jour la liste des paquets
        run: sudo apt update

      - name: Mettre à niveau les paquets installés
        run: sudo apt upgrade -y
