name: Mise à jour Ubuntu

on:
  workflow_dispatch:

jobs:
  update-system:
    runs-on: ubuntu-latest

    steps:
      - name: Mettre à jour et upgrader le système
        run: |
          sudo apt update
          sudo apt upgrade -y
