name: Scan sécurité Terraform

on:
  push:
    branches: [ dev ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'terraform/**'

jobs:
  tfsec-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Scanner avec tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform
